export const COUNTRIES = [
  "United Kingdom",
  "United States",
  "Canada",
  "Australia",
  "New Zealand",
  "India",
  "Ireland",
  "Germany",
  "France",
  "Netherlands",
  "Belgium",
  "Spain",
  "Portugal",
  "Italy",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czechia",
  "Greece",
  "Turkey",
  "Japan",
  "South Korea",
  "Singapore",
  "Hong Kong",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Vietnam",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Israel",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Other / Not Listed",
].sort();

export const ADDRESS_LABELS = ["Home", "Work", "Other"];
